controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

      zuuu_forward_command_controller:
        type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

zuuu_forward_command_controller:
  ros__parameters:
    joints:
      - drivewhl1_joint
      - drivewhl2_joint
      - drivewhl3_joint
    interface_name: velocity
    use_sim_time: true
